name: Sync to Hugging Face hub

on:
  push:
    branches:
      - master  # Or your repository's default branch (e.g., master)

  # Allows running the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Use a recent version of the checkout action
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          lfs: true # Set to true if you use Git LFS for large files

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} # Use the secret you created
        run: |
          # Add the Space as a remote (handles cases where the runner doesn't have it)
          git remote add space https://AhmadAli223:${HF_TOKEN}@huggingface.co/spaces/AhmadAli223/Text2Image || true
          # Push changes to the main branch of the Space repository
          git push --force space HEAD:main # Pushes the current commit to the 'main' branch on the Space remote
